Uses beta14 of SDK and contracts beta 5
hubiinetwork/nahmii-cli pull request #38
Opened 2018-11-13 09:57 UTC by jonbern

Uses beta 5 of contracts.

2018-11-13 11:22 UTC, morfj approved these changes

2018-11-13 11:22 UTC, morfj requested changes
Needs a version bump

2018-11-13 12:18 UTC, jonbern commented
Good catch. I've updated the version now!

2018-11-13 12:49 UTC, morfj approved these changes

2018-11-15 07:43 UTC, liamaharon commented
I think this can be closed. Support for SDK beta 16 merged here https://github.com/hubiinetwork/nahmii-cli/pull/40

2018-11-15 07:43 UTC, closed without merging