Support withdrawal/settlement
hubiinetwork/nahmii-cli pull request #44
Opened 2018-12-11 09:11 UTC by katat

- [x] Support starting challenges.
 - [x] Support settling qualified challenges.
 - [x] Support withdrawal

2018-12-15 10:49 UTC, katat commented on src/commands/stage.js
> +            let totalIntendedStageAmount = txs.reduce((cum, tx) => {
Bingo :)
I will update this name to `accumulator`

2018-12-16 08:32 UTC, katat commented
Sure, I have added the documentation for the new commands.

2019-01-30 06:53 UTC, hubiierik commented on src/commands/settle.js
> +            const {requiredChallenges, invalidReasons} = await settlement.getRequiredChallengesForIntendedStageAmount(stageMonetaryAmount, wallet.address);
Call is missing latestReceipt argument.

2019-01-30 06:56 UTC, hubiierik commented on src/commands/settle.js
> +            const {requiredChallenges, invalidReasons} = await settlement.getRequiredChallengesForIntendedStageAmount(stageMonetaryAmount, wallet.address);
Return value (of promise) is an array. It cannot be unpacked.

2019-05-13 06:09 UTC, morfj requested changes
Should we also add an "unstage" command, or should that functionality be included in the deposit command?

2019-05-13 06:09 UTC, morfj commented on src/commands/settle.js
> +    command: 'settle <stageAmount> <currency> [--gas=<gasLimit> --price=<gasPrice in gwei>]',
stageAmount => amount?

2019-05-13 06:39 UTC, katat commented
@morfj Thanks for the comments. I think it is a good idea to add the "unstage" command. I will make the updates according to the comments.

2019-05-13 06:40 UTC, morfj commented
I think this PR could very well be labeled as v1.0.0 of the CLI :+1:

2019-06-04 06:38 UTC, morfj commented on src/commands/settle.js
> +        const tokenInfo = await provider.getTokenInfo(currency);
This async call is now done outside of the try...catch scope => unhandled rejection if it fails

2019-06-04 06:38 UTC, morfj commented on src/commands/stage.js
> +        const tokenInfo = await provider.getTokenInfo(currency);
Also outside of try...catch scope

2019-06-04 06:38 UTC, morfj commented on src/commands/stage.js
> +function validatePositiveInteger(str) {
We could move this common function to the utils module I think.

2019-06-04 06:40 UTC, morfj commented on src/commands/unstage.js
> +        const tokenInfo = await provider.getTokenInfo(argv.currency);
async outside try...catch

2019-06-04 06:40 UTC, morfj commented on src/commands/stage.js
> +function validatePositiveInteger(str) {
Great minds think alike.. 🤣

2019-06-04 06:49 UTC, morfj reviewed
Maybe add a paragraph in the README about how you are supposed to use the settle, stage, withdraw commands in conjunction with each other, and indicate the "typical time" in between invocations. It would help explain the whole settlement process for the uninitiated I think.

2019-06-04 15:38 UTC, morfj approved these changes

2019-06-04 23:14 UTC, merged